name: StepCOVNet Application

on: [push]
env:
  COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
  COVERALLS_GIT_BRANCH: "${{ github.ref }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6    
    - name: Install madmom dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install scipy
        pip install Cython
        pip install mido
    - name: Install rest of dependencies
      run: |
        sudo apt-get install libsndfile1
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-mock
        pytest
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

